const countries = [
    "Åland Islands",
    "Albania",
    "Andorra",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Belarus",
    "Belgium",
    "Bosnia & Herzegovina",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Canada",
    "Chile",
    "Colombia",
    "Cook Islands",
    "Costa Rica",
    "Croatia",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Polynesia",
    "Georgia",
    "Germany",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Guadaloupe",
    "Guernsey",
    "Hong Kong SAR",
    "Iceland",
    "India",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Japan",
    "Jersey",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Latvia",
    "Lichtenstein",
    "Lithuania",
    "Luxembourg",
    "Malaysia",
    "Malta",
    "Mayotte",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Nauru",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Niue",
    "Norfolk Island",
    "North Macedonia",
    "Norway",
    "Pakistan",
    "Papua New Guinea",
    "Philippines",
    "Pitcairn Islands",
    "Poland",
    "Portugal",
    "Qatar",
    "Réunion",
    "Samoa",
    "San Maria",
    "Saudi Arabia",
    "Serbia",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "South Africa",
    "South Korea",
    "Spain",
    "Svalbard & Jan Mayen",
    "Sweden",
    "Switzerland",
    "Taiwan",
    "Timor-Leste",
    "Tokelau",
    "Tonga",
    "Türkiye",
    "Tuvalu",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Vanuatu",
    "Vatican City",
    "Wallis & Futuna"
];
export default countries;
